#!/usr/bin/env bash

###
# At EOD, 7:59PM ET (11:59PM UTC - 23:59UTC) - this script runs, which runs a python script to export all the tickers for the day.
###

# Need to do this to get access to ssmtp
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"

# Secret
LPS_PASSWORD="P0t4t03Fr3nc4fr1e3!"
ADDRESS_DEST="6464643484@txt.att.net"
ABSOLUTE_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MAIL_HEADER_PATH="${ABSOLUTE_PATH}/mail_header.txt"
PATH_TO_CSV_EXPORTER="$(echo $ABSOLUTE_PATH | sed -e 's/\/crons$//g')/CsvExporter/main.py"
SYMBOLS="SPY,QQQ,ARKK,ARKG,ARKF,TSLA,AAPL,SNOW,TSM,SHOP,TTD,CRM,EXAS,NIO,AMD,ZM,AMZN,PTON,SNAP,TWTR,DIS,PLUG,DAL,ACB,BAC,APHA,FIT,NFLX,FB,PLTR,T,NKLA,WORK,DDOG,CLDR,TQQQ,SQQQ,GE,AAL,F"

echo "running from $ABSOLUTE_PATH";

DB_CONTAINER_NAME=`docker ps --format '{{.Names}}' --filter name=^/last-price-saver_lps-db`
if [ -z "$DB_CONTAINER_NAME" ]; then
    MSG="ERROR: It appears the the db container may not be currently running";
    (cat $MAIL_HEADER_PATH && echo "$MSG") | ssmtp $ADDRESS_DEST
    exit 1;
fi
echo "DB_CONTAINER_NAME is set to '$DB_CONTAINER_NAME'\n" >> /tmp/auto_export_csv_$(date +"%Y-%m-%d")

DB_CONTAINER_IP=`docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $DB_CONTAINER_NAME`
if [ -z "$DB_CONTAINER_IP" ]; then
    MSG="ERROR: Unable to get the ip address of the db container";
    (cat $MAIL_HEADER_PATH && echo "$MSG") | ssmtp $ADDRESS_DEST
    exit 1;
fi
echo "DB_CONTAINER_IP is set to '$DB_CONTAINER_IP'\n" >> /tmp/auto_export_csv_$(date +"%Y-%m-%d")

CURRENT_YEAR=$((10#$(date +"%Y")))
echo "The current year as number: $CURRENT_YEAR\n" >> /tmp/auto_export_csv_$(date +"%Y-%m-%d")

CURRENT_MONTH=$((10#$(date +"%m")))
echo "The current month as number: $CURRENT_MONTH\n" >> /tmp/auto_export_csv_$(date +"%Y-%m-%d")

CURRENT_DAY=$((10#$(date +"%d")))
echo "The current day as number: $CURRENT_DAY\n" >> /tmp/auto_export_csv_$(date +"%Y-%m-%d")

RUN_CMD="python3 $PATH_TO_CSV_EXPORTER $CURRENT_YEAR $CURRENT_MONTH $CURRENT_DAY $DB_CONTAINER_IP $LPS_PASSWORD \"$SYMBOLS\""
OUTPUT=$(eval $RUN_CMD)
echo $OUTPUT
# if [[ "$DAY_AMT" == 0 ]]; then
#     MSG="ERROR: There appears to be no rows from today in the DB. TDA api token expired? (YEAR:${CURRENT_YEAR}, MONTH:${CURRENT_MONTH}, DAY:${CURRENT_DAY})";
#     (cat $MAIL_HEADER_PATH && echo "$MSG") | ssmtp $ADDRESS_DEST
#     exit 1;
# fi
# echo "Rows for today so far: $DAY_AMT\n" >> /tmp/auto_export_csv_$(date +"%Y-%m-%d")


# YEAR=2021
# MONTH=5
# DAY=10
